In [1]:
import tensorflow


C:\Users\PUKHRAJ\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\PUKHRAJ\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\PUKHRAJ\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\PUKHRAJ\Anaconda3\envs\tensorflow\lib\site-

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset  = pd.read_csv("Churn_Modelling.csv")
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le = LabelEncoder()
dataset['Geography'] = le.fit_transform(dataset['Geography'])
dataset['Gender'] = le.fit_transform(dataset['Gender'])

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   
1          2    15647311      Hill          608          2       0   41   
2          3    15619304      Onio          502          0       0   42   
3          4    15701354      Boni          699          0       0   39   
4          5    15737888  Mitchell          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
dataset.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography            int32
Gender               int32
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [7]:
x = dataset.iloc[:,3:13].values
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [6.0800000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [5.0200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [8]:
y = dataset.iloc[:,13].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.25, random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


In [14]:
x_train.shape

(7500, 10)

In [15]:
import keras

from keras.models import Sequential
from keras.layers import Dense


In [16]:
clf = Sequential()

clf.add(Dense(output_dim=6, init='uniform', activation='relu', input_dim=10)) #1st hidden layer

clf.add(Dense(output_dim=6, init='uniform', activation='relu')) #2nd hidden layer

clf.add(Dense(output_dim=3, init='uniform', activation='relu')) #3nd hidden layer
              
clf.add(Dense(output_dim=1, init='uniform', activation='sigmoid')) # output layer
                          

C:\Users\PUKHRAJ\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=10, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\PUKHRAJ\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """
C:\Users\PUKHRAJ\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=3, kernel_initializer="uniform")`
  import sys
C:\Users\PUKHRAJ\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  if __name__ == '__main__':


In [32]:
clf.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
clf.fit(x_train, y_train, batch_size=10, nb_epoch=50)

C:\Users\PUKHRAJ\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/500
7500/7500 [==============================] - 2s 200us/step - loss: 0.4889 - acc: 0.7956
Epoch 2/500
7500/7500 [==============================] - 1s 144us/step - loss: 0.4317 - acc: 0.7963
Epoch 3/500
7500/7500 [==============================] - 1s 146us/step - loss: 0.4272 - acc: 0.7963
Epoch 4/500
7500/7500 [==============================] - 1s 135us/step - loss: 0.4231 - acc: 0.8095
Epoch 5/500
7500/7500 [==============================] - 1s 137us/step - loss: 0.4210 - acc: 0.8237
Epoch 6/500
7500/7500 [==============================] - 1s 144us/step - loss: 0.4193 - acc: 0.8271
Epoch 7/500
7500/7500 [==============================] - 1s 142us/step - loss: 0.4171 - acc: 0.8291
Epoch 8/500
7500/7500 [==============================] - 1s 140us/step - loss: 0.4158 - acc: 0.8297
Epoch 9/500
7500/7500 [==============================] - 1s 136us/step - loss: 0.4142 - acc: 0.8305
Epoch 10/500
7500/7500 [==============================] - 1s 138us/step - loss: 0.4130 - acc: 0.8317

7500/7500 [==============================] - 1s 132us/step - loss: 0.3938 - acc: 0.8367
Epoch 83/500
7500/7500 [==============================] - 1s 136us/step - loss: 0.3940 - acc: 0.8369
Epoch 84/500
7500/7500 [==============================] - 1s 137us/step - loss: 0.3941 - acc: 0.8379
Epoch 85/500
7500/7500 [==============================] - 1s 135us/step - loss: 0.3946 - acc: 0.8364
Epoch 86/500
7500/7500 [==============================] - 1s 140us/step - loss: 0.3945 - acc: 0.8365
Epoch 87/500
7500/7500 [==============================] - 1s 139us/step - loss: 0.3940 - acc: 0.8357
Epoch 88/500
7500/7500 [==============================] - 1s 138us/step - loss: 0.3945 - acc: 0.8365
Epoch 89/500
7500/7500 [==============================] - 1s 139us/step - loss: 0.3941 - acc: 0.8352
Epoch 90/500
7500/7500 [==============================] - 1s 138us/step - loss: 0.3940 - acc: 0.8353
Epoch 91/500
7500/7500 [==============================] - 1s 135us/step - loss: 0.3938 - acc: 0.8352
Epo

7500/7500 [==============================] - 1s 143us/step - loss: 0.3931 - acc: 0.8368
Epoch 163/500
7500/7500 [==============================] - 1s 144us/step - loss: 0.3930 - acc: 0.8356
Epoch 164/500
7500/7500 [==============================] - 1s 145us/step - loss: 0.3927 - acc: 0.8343
Epoch 165/500
7500/7500 [==============================] - 1s 145us/step - loss: 0.3932 - acc: 0.8356
Epoch 166/500
7500/7500 [==============================] - 1s 145us/step - loss: 0.3929 - acc: 0.8367
Epoch 167/500
7500/7500 [==============================] - 1s 145us/step - loss: 0.3928 - acc: 0.8359
Epoch 168/500
7500/7500 [==============================] - 1s 145us/step - loss: 0.3928 - acc: 0.8356
Epoch 169/500
7500/7500 [==============================] - 1s 144us/step - loss: 0.3932 - acc: 0.8368
Epoch 170/500
7500/7500 [==============================] - 1s 145us/step - loss: 0.3926 - acc: 0.8371
Epoch 171/500
7500/7500 [==============================] - 1s 142us/step - loss: 0.3930 - acc: 0

7500/7500 [==============================] - 1s 138us/step - loss: 0.3924 - acc: 0.8375
Epoch 243/500
7500/7500 [==============================] - 1s 143us/step - loss: 0.3926 - acc: 0.8367
Epoch 244/500
7500/7500 [==============================] - 1s 139us/step - loss: 0.3924 - acc: 0.8372
Epoch 245/500
7500/7500 [==============================] - 1s 142us/step - loss: 0.3922 - acc: 0.8367
Epoch 246/500
7500/7500 [==============================] - 1s 143us/step - loss: 0.3927 - acc: 0.8363
Epoch 247/500
7500/7500 [==============================] - 1s 142us/step - loss: 0.3924 - acc: 0.8361
Epoch 248/500
7500/7500 [==============================] - 1s 141us/step - loss: 0.3921 - acc: 0.8363
Epoch 249/500
7500/7500 [==============================] - 1s 143us/step - loss: 0.3924 - acc: 0.8363
Epoch 250/500
7500/7500 [==============================] - 1s 143us/step - loss: 0.3924 - acc: 0.8349
Epoch 251/500
7500/7500 [==============================] - 1s 142us/step - loss: 0.3924 - acc: 0

7500/7500 [==============================] - 1s 141us/step - loss: 0.3770 - acc: 0.8433
Epoch 323/500
7500/7500 [==============================] - 1s 145us/step - loss: 0.3735 - acc: 0.8477
Epoch 324/500
7500/7500 [==============================] - 1s 144us/step - loss: 0.3689 - acc: 0.8487
Epoch 325/500
7500/7500 [==============================] - 1s 142us/step - loss: 0.3648 - acc: 0.8524
Epoch 326/500
7500/7500 [==============================] - 1s 143us/step - loss: 0.3610 - acc: 0.8529
Epoch 327/500
7500/7500 [==============================] - 1s 144us/step - loss: 0.3596 - acc: 0.8555
Epoch 328/500
7500/7500 [==============================] - 1s 144us/step - loss: 0.3581 - acc: 0.8585
Epoch 329/500
7500/7500 [==============================] - 1s 143us/step - loss: 0.3570 - acc: 0.8584
Epoch 330/500
7500/7500 [==============================] - 1s 141us/step - loss: 0.3563 - acc: 0.8564
Epoch 331/500
7500/7500 [==============================] - 1s 145us/step - loss: 0.3551 - acc: 0

7500/7500 [==============================] - 1s 137us/step - loss: 0.3457 - acc: 0.8607
Epoch 403/500
7500/7500 [==============================] - 1s 138us/step - loss: 0.3455 - acc: 0.8599
Epoch 404/500
7500/7500 [==============================] - 1s 142us/step - loss: 0.3455 - acc: 0.8607
Epoch 405/500
7500/7500 [==============================] - 1s 138us/step - loss: 0.3461 - acc: 0.8595
Epoch 406/500
7500/7500 [==============================] - 1s 139us/step - loss: 0.3457 - acc: 0.8621
Epoch 407/500
7500/7500 [==============================] - 1s 142us/step - loss: 0.3458 - acc: 0.8613
Epoch 408/500
7500/7500 [==============================] - 1s 141us/step - loss: 0.3453 - acc: 0.8605
Epoch 409/500
7500/7500 [==============================] - 1s 147us/step - loss: 0.3454 - acc: 0.8620
Epoch 410/500
7500/7500 [==============================] - 1s 137us/step - loss: 0.3452 - acc: 0.8631
Epoch 411/500
7500/7500 [==============================] - 1s 137us/step - loss: 0.3453 - acc: 0

7500/7500 [==============================] - 1s 143us/step - loss: 0.3422 - acc: 0.8604
Epoch 483/500
7500/7500 [==============================] - 1s 139us/step - loss: 0.3417 - acc: 0.8599
Epoch 484/500
7500/7500 [==============================] - 1s 134us/step - loss: 0.3420 - acc: 0.8605
Epoch 485/500
7500/7500 [==============================] - 1s 140us/step - loss: 0.3416 - acc: 0.8603
Epoch 486/500
7500/7500 [==============================] - 1s 134us/step - loss: 0.3416 - acc: 0.8621
Epoch 487/500
7500/7500 [==============================] - 1s 136us/step - loss: 0.3411 - acc: 0.8608
Epoch 488/500
7500/7500 [==============================] - 1s 141us/step - loss: 0.3409 - acc: 0.8609
Epoch 489/500
7500/7500 [==============================] - 1s 135us/step - loss: 0.3415 - acc: 0.8595
Epoch 490/500
1850/7500 [======>.......................] - ETA: 0s - loss: 0.3478 - acc: 0.8503

In [17]:
y_pred = clf.predict(x_test)
y_pred

array([[0.5000008 ],
       [0.50000036],
       [0.5       ],
       ...,
       [0.5       ],
       [0.5       ],
       [0.5       ]], dtype=float32)

In [22]:
y_pred=(y_pred>0.5)

from sklearn.metrics import confusion_matrix
from sklearn import metrics

cm = confusion_matrix(y_test, y_pred)

In [23]:
cm

array([[ 732, 1259],
       [ 196,  313]], dtype=int64)