In [9]:
def generate email(a,b,c):
a = input("ENTER THE FIRST NAME:")
b = input("ENTER THE LAST NAME:")
C = input("ENTER THE DOB DD/MM/YYYY:")


SyntaxError: invalid syntax (<ipython-input-9-ddc6204ab448>, line 1)

In [20]:
def generate_email():
    
    a = input("ENTER THE FIRST NAME:")
    b = input("ENTER THE LAST NAME:")
    c = input("ENTER THE DOB DD/MM/YYYY:")
        
    email = ""
    
    email = email + a[0:2].lower()
    email = email + b[0].lower()
    email = email + c.replace("/","") + "@xyz.com"
    return email
email = generate_email()
print("email", email)



ENTER THE FIRST NAME:pukhraj
ENTER THE LAST NAME:suthar
ENTER THE DOB DD/MM/YYYY:02/03/199
email pus0203199@xyz.com


In [48]:
matrix = np.random.randint(0,255,(3,3))
print(matrix)
matrix1 = np.full((3,3),10)
print(matrix1)
c = matrix-matrix1
print(c)

[[148  51 126]
 [215 142 139]
 [210 230 213]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[138  41 116]
 [205 132 129]
 [200 220 203]]


[1, 2, 3, 4, 5, 6]

In [21]:
import numpy as np

In [23]:


matrix = np.random.randint(0,255,(3,3))
matrix

array([[252,  63,  83],
       [ 46, 113,  87],
       [163,  48, 233]])

In [25]:
matrix1 = np.full((3,3),10)
matrix1

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [26]:
matrix-matrix1

array([[242,  53,  73],
       [ 36, 103,  77],
       [153,  38, 223]])

In [27]:
np.subtract(matrix,matrix1)

array([[242,  53,  73],
       [ 36, 103,  77],
       [153,  38, 223]])

In [42]:
s = []
for i in range(9):
    s.append(int(input('enter the value:')))
s.sort()
mean = np.mean(s)
median = np.median(s)
    
if mean > median:
    print ("positive skewed")
elif mean < median:
    print("negative skewed")
else:
    print ("normal curve")


enter the value:12
enter the value:41
enter the value:10
enter the value:15
enter the value:15
enter the value:14
enter the value:47
enter the value:42
enter the value:47
positive skewed


In [29]:
8

[2, 5, 51, 1, 24, 54, 65, 65, 55]


In [30]:
s.sort()

In [31]:
s

[1, 2, 5, 24, 51, 54, 55, 65, 65]

In [38]:
mean = np.mean(s)

In [39]:
median = np.median(s)

array([ 1,  2,  5, 24, 51, 54, 55, 65, 65])

In [40]:
if mean > median:
    print ("positive skewed")
elif mean < median:
    print("negative skewed")
else:
    print ("normal curve")


negative skewed


In [44]:
x1 = int(input("ENTER THE  x1 cordinate:"))
x2 = int(input("ENTER THE x2  cordinate:"))
y1 = int(input("ENTER THE  y1 cordinate:"))
y2 = int(input("ENTER THE  y2 cordinate:"))
s =np.sqrt((x2-x1)**2+(y2-y1)**2)
p = np.abs(x2-x1) + np.abs(y2-y1)
print(s,"euclidean diatance")
print(p,"manhattan distance")

ENTER THE  x1 cordinate:10
ENTER THE x2  cordinate:12
ENTER THE  y1 cordinate:4
ENTER THE  y2 cordinate:45
41.048751503547585 euclidean diatance
43 manhattan distance


In [46]:
s = []
for i in range(4):
    s.append(int(input('enter the value:')))
l = np.exp(s)
d = np.sum(l)
total = l/d
print(total)
print(np.sum(total))


enter the value:1
enter the value:2
enter the value:3
enter the value:4
[0.0320586  0.08714432 0.23688282 0.64391426]
1.0
