Assingment4_pukhraj

1.find factorial

In [1]:
import numpy as np

In [2]:
n = int(input("enter the values:"))
np.multiply.accumulate(np.arange(1,n+1))

enter the values:5


array([  1,   2,   6,  24, 120], dtype=int32)

2.summarizing data

In [3]:
import pandas as pd

In [15]:
da = pd.read_csv('data.csv')
print(da)
x = np.max(da)
y = np.min(da)
z = np.mean(da)
a = np.std(da)
b = np.var(da)
c = np.quantile(da,0.25)
d = np.quantile(da,0.5)
e = np.quantile(da,0.75)
print(x,y,z,a,b,c,d,e)

    Values
0   428.00
1   989.00
2   662.00
3   723.00
4   957.00
5   256.00
6   931.00
7   376.00
8   837.00
9   539.00
10  763.00
11  458.00
12  749.00
13  340.00
14  522.00
15  806.00
16  412.00
17  687.00
18  941.00
19  973.00
20  757.00
21  927.00
22  459.00
23    3.32
24  445.00
25   92.20
26  248.00
27  597.00
28  153.00
29  739.00
Values    989.0
dtype: float64 Values    3.32
dtype: float64 Values    592.317333
dtype: float64 Values    275.639327
dtype: float64 Values    75977.038713
dtype: float64 416.0 629.5 795.25


3.Student Report

In [25]:
x = np.array([[45,60,55,70,70,38],[39,48,88,42,37,38],[32,77,60,39,71,38]])
print(x)
a = []
l = []
for i in range(6):
    m = np.max(x[ : ,i])
    l.append(m)
    n = np.min(x[ : ,i])
    a.append(n)
print("maximun in all subject",l)
print("minimum in all subject",a)

    
    
    

[[45 60 55 70 70 38]
 [39 48 88 42 37 38]
 [32 77 60 39 71 38]]
maximun in all subject [45, 77, 88, 70, 71, 38]
minimum in all subject [32, 48, 55, 39, 37, 38]
