In [14]:
a = int(input("enter the base:"))
h = int(input("enter the height:"))
class Area:
    def triangle(self,a,h):
        self.a = a
        self.h = h
        total = (1/2*(a*h))
        return total
x = Area()
ans = x.triangle(a,h)
print(ans)

enter the base:10
enter the height:10
50.0


In [18]:
a = input('enter value of a')
b = input('enter value of b')
if a == b:
    print("a and b are same")
    
    

enter value of a10
enter value of b10
a and b are same


In [22]:
a = int(input('enter value of a'))
#b = int(input('enter value of b'))
if a%2 == 0:
     print("a is even")
    
else:
    print('a is odd')

enter value of a13
a is odd


In [ ]:
if expression:
    statement(S)
    
elif expression2:
    statement(s)
    
elif expression:
    statement(s)
    
else:

In [20]:
4%2

0

In [2]:
s = "*"
for row in range (0,7):
    for column in range(0,7):
        if ( column == 1 or (row == 6 and column != 0 and column<6)):
            
        
            
            
            
    

s 
s 
s 
s 
s 
s 
s 
s 
s 
s 
s 


In [1]:
 s = ""
for i in range(5):
    for j in range(5):
        if (i == 0 and j == 0 ) or (i == 0 and j == 4) or (i == 1 and j == 1) or (i == 1 and j == 3) or (i == 2 and j == 2) or (i == 3 and j == 1) or (i == 3 and j == 3) or (i == 4 and j == 0) or (i == 0 and j == 4) or (i == 5 and j == 0) or (i == 5 and j == 5):
            s = s+"*"
        else:
            s = s+" "
    s=s+"\n"
print(s)


*   *
 * * 
  *  
 * * 
*    



In [7]:
a = int(input("enter the number:"))
def square(a):
     return(a*a)
#square(a)
print(square(a))

enter the number:10
100


In [8]:
a = int(input("enter the number:"))
def squareroot(x):
    return(x**(1/2))
print(squareroot(a))

enter the number:25
5.0


In [19]:
a = int(input("enter the number:"))
b = int(input("enter the number:"))
class calculator:
    def addition(a,b):
        c = a + b
        return(c)
    print("addition:", addition (a,b))

    def multiply(a,b):
        c = a*b
        return(c)
    print("multiply:", multiply (a,b))

    def division(a,b):
        c = a/b
        return(c)
    print("division:", division (a,b))
        

enter the number:25
enter the number:25
addition: 50
multiply: 625
division: 1.0


In [9]:
)a = int(input("enter the number:")
class calculator:
    
    def square(a):
        
        return(a*a)
    print(square(a))

    def squareroot(x):
        
        return(x**(1/2))
    print(squareroot(a))


enter the number:12
144
3.4641016151377544


In [4]:
s = []
for i in range(1,12,3):
    x = int(input("enter no.:"))
    s.append(x)
def addition(t):
    t = 0
    for i in s:
        t = t+i
    return(t)
print("addition:",addition(s))

def multiply(t):
    t=1
    for i in s:
        t=t*i
    return(t)
print("multiply:",multiply(s))

enter no.:10
enter no.:10
enter no.:10
enter no.:10
addition: 40
multiply: 10000


In [3]:
import numpy as np
np.__version__
np?
np

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [ ]:
from numpy import *

In [2]:
l = []
l = list(range(10))
l
l2 = [str(c) for c in (l)]
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [11]:
np.array([1.567888, 2, 3, 4, 5, 6]).dtype

dtype('float64')

In [19]:
np.array([1.567888883, 2, 3, 4, 5, 6],dtype='float64')

array([1.56788888, 2.        , 3.        , 4.        , 5.        ,
       6.        ])

In [23]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
np.random.normal(,1,(100,100))

array([[ 3.86814652e-02,  1.05842377e-03, -3.63633236e-02, ...,
         1.47244184e+00, -2.33634552e-01,  1.38456036e+00],
       [ 9.84299940e-01, -7.43954575e-01, -7.14686814e-01, ...,
         1.02934296e+00, -7.42920679e-01,  5.50852031e-01],
       [ 5.72258347e-02,  1.28552211e+00,  1.63830107e+00, ...,
        -1.49605771e+00,  7.86967330e-01,  7.97332655e-01],
       ...,
       [-1.20015265e+00, -1.35495302e+00, -1.28447652e+00, ...,
        -1.29384758e+00,  9.20913157e-01, -4.01080006e-01],
       [-1.19007624e+00, -1.16494411e-01,  8.70037017e-01, ...,
        -1.40356198e+00, -5.25422842e-01, -1.01560399e+00],
       [ 9.07444655e-01, -5.03223273e-01,  8.32342640e-01, ...,
         6.08411831e-02,  6.94572174e-02,  6.68785586e-01]])

In [13]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [15]:
np.random.random((((4,4,4,4))))

array([[[[1.94033201e-01, 3.15241223e-01, 5.37715645e-01,
          9.60846667e-01],
         [1.33442986e-01, 6.29265134e-01, 7.80012117e-01,
          5.54227827e-01],
         [1.67777402e-03, 2.90981149e-01, 5.71994179e-01,
          3.00337715e-01],
         [5.71364988e-03, 4.83326552e-01, 5.24885197e-01,
          1.41572683e-01]],

        [[7.24815264e-01, 1.92357868e-01, 5.97882540e-01,
          1.14192505e-01],
         [3.32528055e-01, 6.89734879e-01, 3.76092869e-01,
          8.94484372e-01],
         [5.28321944e-01, 8.01573942e-01, 1.54555058e-01,
          5.09146096e-01],
         [4.25661055e-01, 3.68293714e-01, 8.39616405e-01,
          8.43664919e-01]],

        [[5.48112387e-01, 4.85144106e-01, 1.41780761e-01,
          1.72998074e-01],
         [7.27539615e-01, 2.65251064e-01, 5.67135431e-01,
          5.36674520e-01],
         [8.59198120e-01, 5.87785516e-01, 3.46085446e-01,
          3.30348860e-01],
         [4.50607099e-01, 9.55888619e-01, 8.10353801e-01,
   

In [27]:
np.random.randint(0,5,(4,4))

array([[2, 4, 2, 4],
       [2, 0, 1, 3],
       [4, 4, 2, 0],
       [0, 4, 0, 0]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.zeros((4,5,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [60]:
def fibonacci(n):
    if n < 0:
        return('incorrect input')
    elif n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        return fibonacci(n-1)+fibonacci(n-2)
    
print(fibonacci(12))

89


In [17]:
l = [22,25,35,45,25]
l1 = [30,35,20,40,55]
t = [l[0]+l1[0],l[1]+l1[1],l[2]+l1[2],l[3]+l1[3],l[4]+l1[4]]
total = max(t)

for i in range (5):
        x.append(t[i]*100/total)
print(x)

    

[61.1764705882353, 70.58823529411765, 64.70588235294117, 100.0, 94.11764705882354]
