In [1]:
import numpy as np

In [2]:
x = np.random.randint(0,10,(4,6))
x

array([[6, 6, 3, 0, 6, 3],
       [1, 2, 0, 7, 0, 4],
       [1, 6, 3, 7, 8, 5],
       [9, 1, 1, 0, 0, 8]])

In [6]:
np.sort(x ,axis=0)


array([[1, 1, 0, 0, 0, 3],
       [1, 2, 1, 0, 0, 4],
       [6, 6, 3, 7, 6, 5],
       [9, 6, 3, 7, 8, 8]])

In [13]:
x = np.array([8,5,6,7,9,1,2,45,4,5,10])
print(x)
print(np.sort(x))
np.partition(x,5)

[ 8  5  6  7  9  1  2 45  4  5 10]
[ 1  2  4  5  5  6  7  8  9 10 45]


array([ 1,  2,  4,  5,  5,  6,  7,  8, 45,  9, 10])

In [19]:
x = np.random.randint(0,10,(4,6))
x

array([[1, 1, 7, 8, 1, 1],
       [6, 5, 2, 0, 8, 9],
       [4, 0, 7, 4, 7, 7],
       [0, 0, 3, 9, 0, 0]])

In [29]:
np.partition(x,2, axis=1)
print((np.sort((x),axis=0)))

[[0 0 2 0 0 0]
 [1 0 3 4 1 1]
 [4 1 7 8 7 7]
 [6 5 7 9 8 9]]
